name: build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: buildCache
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload code average
        uses: actions/upload-artifact@v4.6.2
        with:
          name: codeaverage
          path: coverage
      - name: build
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build
          path: build
